# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20160413_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
